"""
QA (Quality Assurance) Agent implementation.

Generates real pytest test functions matching each acceptance criterion in the PM TaskList,
executes them inside an isolated sandboxed subprocess (with wall-clock timeouts, memory/CPU resource caps,
and network isolation where available), and parses actual test results into a QAReport object.
"""

import importlib.util
import os
import re
import subprocess
import sys
import tempfile
from typing import List, Tuple

try:
    import resource
except ImportError:
    resource = None

from src.schema import GeneratedComponent, QAReport, TaskList, TestResult


def _network_isolation_available() -> bool:
    """
    Checks if 'unshare --net' is supported by the host OS.
    Prevents generated tests from executing network calls if unshare namespace isolation is available.
    """
    try:
        r = subprocess.run(["unshare", "--net", "true"], capture_output=True, timeout=3)
        return r.returncode == 0
    except (FileNotFoundError, OSError, subprocess.TimeoutExpired):
        return False


_HAS_NETNS = _network_isolation_available()


def _limit_resources():
    """
    Child preexec_fn process limit hook.
    Sets memory, CPU, file size, and file descriptor limits on POSIX platforms to isolate execution.
    """
    if resource is None:
        return
    try:
        resource.setrlimit(resource.RLIMIT_AS, (256 * 1024 * 1024, 256 * 1024 * 1024))
        resource.setrlimit(resource.RLIMIT_CPU, (10, 10))
        resource.setrlimit(resource.RLIMIT_FSIZE, (1024 * 1024, 1024 * 1024))
        resource.setrlimit(resource.RLIMIT_NOFILE, (64, 64))
    except Exception:
        pass


def _generate_stub_pytest_code(backend_file_path: str, task_list: TaskList) -> str:
    """
    Generates deterministic pytest test code using FastAPI TestClient targeting backend_file_path.
    
    Why importlib module loading is used in the test script:
    Dynamically importing backend_file_path via importlib ensures the test runner can target any generated
    backend file on disk regardless of sys.path configuration or current working directory.
    """
    escaped_path = backend_file_path.replace("\\", "\\\\")

    pytest_code = f'''"""
Automated Pytest Suite generated by QA Agent targeting {escaped_path}.
"""

import importlib.util
import pytest
from fastapi.testclient import TestClient

spec = importlib.util.spec_from_file_location("generated_backend", r"{escaped_path}")
backend_mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(backend_mod)
app = backend_mod.app
client = TestClient(app)

# Task 1: POST /todos endpoint acceptance criteria
def test_add_todo_accepts_title():
    res = client.post("/todos", json={{"title": "Buy groceries"}})
    assert res.status_code == 201 or res.status_code == 200
    data = res.json()
    assert "title" in data
    assert data["title"] == "Buy groceries"

def test_add_todo_returns_id_and_default_completed():
    res = client.post("/todos", json={{"title": "Read book"}})
    assert res.status_code == 201 or res.status_code == 200
    data = res.json()
    assert "id" in data
    assert data.get("completed") is False

# Task 2: GET /todos endpoint acceptance criteria
def test_list_todos_returns_array():
    res = client.get("/todos")
    assert res.status_code == 200
    data = res.json()
    assert "todos" in data or isinstance(data, list)

def test_list_todos_item_schema():
    client.post("/todos", json={{"title": "Test todo item"}})
    res = client.get("/todos")
    data = res.json()
    todos = data.get("todos", data) if isinstance(data, dict) else data
    assert len(todos) > 0
    item = todos[0]
    assert "id" in item
    assert "title" in item
    assert "completed" in item

# Task 3: PUT /todos/{{todo_id}}/complete acceptance criteria
def test_complete_todo_updates_flag():
    post_res = client.post("/todos", json={{"title": "Complete me"}})
    todo_id = post_res.json()["id"]
    put_res = client.put(f"/todos/{{todo_id}}/complete")
    assert put_res.status_code == 200
    data = put_res.json()
    assert data["completed"] is True

def test_complete_todo_returns_updated():
    post_res = client.post("/todos", json={{"title": "Verify update return"}})
    todo_id = post_res.json()["id"]
    put_res = client.put(f"/todos/{{todo_id}}/complete")
    assert put_res.status_code == 200
    assert put_res.json()["id"] == todo_id

# Task 4: DELETE /todos/{{todo_id}} acceptance criteria
def test_delete_todo_removes_item():
    post_res = client.post("/todos", json={{"title": "Delete me"}})
    todo_id = post_res.json()["id"]
    del_res = client.delete(f"/todos/{{todo_id}}")
    assert del_res.status_code == 200

def test_delete_todo_returns_confirmation():
    post_res = client.post("/todos", json={{"title": "Delete confirmation"}})
    todo_id = post_res.json()["id"]
    del_res = client.delete(f"/todos/{{todo_id}}")
    assert del_res.status_code == 200
    assert "status" in del_res.json() or "message" in del_res.json() or del_res.json() == {{"status": "deleted"}}
'''
    return pytest_code


def run_qa_agent(
    task_list: TaskList,
    backend_comp: GeneratedComponent,
    output_dir: str,
    use_real: bool = False,
) -> QAReport:
    """
    Executes the QA Agent to write and execute a real pytest suite against backend_comp.

    Why execution must be a real sandboxed subprocess:
    Asking an LLM to guess whether code passes tests leads to false confidence.
    Executing pytest in an isolated subprocess with resource limits captures true runtime pass/fail status.
    """
    os.makedirs(output_dir, exist_ok=True)
    test_file_path = os.path.abspath(os.path.join(output_dir, "test_backend_generated.py"))

    if not use_real:
        pytest_code = _generate_stub_pytest_code(backend_comp.file_path, task_list)
    else:
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY environment variable is required for real mode execution.")

        from langchain_groq import ChatGroq

        llm = ChatGroq(
            model="llama-3.3-70b-versatile",
            temperature=0,
            api_key=api_key,
        )

        criteria_list = []
        for t in task_list.tasks:
            for c in t.acceptance_criteria:
                criteria_list.append(f"- {t.description}: {c}")
        criteria_str = "\n".join(criteria_list)

        escaped_path = backend_comp.file_path.replace("\\", "\\\\")

        prompt = f"""You are a Lead QA Engineer.
Write a valid pytest python file targeting the generated FastAPI application at path '{escaped_path}'.
Write AT LEAST one test function per acceptance criterion below.
Import the app using:
```python
import importlib.util
from fastapi.testclient import TestClient
spec = importlib.util.spec_from_file_location("generated_backend", r"{escaped_path}")
backend_mod = importlib.util.module_from_spec(spec)
spec.loader.exec_module(backend_mod)
app = backend_mod.app
client = TestClient(app)
```

Acceptance Criteria:
{criteria_str}

Return ONLY raw Python pytest code inside a ```python ``` block.
"""
        response = llm.invoke(prompt)
        raw_text = str(response.content)

        if "```python" in raw_text:
            pytest_code = raw_text.split("```python")[1].split("```")[0].strip()
        elif "```" in raw_text:
            pytest_code = raw_text.split("```")[1].split("```")[0].strip()
        else:
            pytest_code = raw_text.strip()

    with open(test_file_path, "w", encoding="utf-8") as f:
        f.write(pytest_code)

    # Run pytest in sandboxed subprocess
    with tempfile.TemporaryDirectory() as sandbox_dir:
        cmd = [sys.executable, "-m", "pytest", test_file_path, "-v", "--tb=short"]
        if _HAS_NETNS:
            cmd = ["unshare", "--net"] + cmd

        preexec = _limit_resources if os.name != "nt" else None

        try:
            proc = subprocess.run(
                cmd,
                cwd=sandbox_dir,
                capture_output=True,
                text=True,
                timeout=15.0,
                preexec_fn=preexec,
            )
            stdout = proc.stdout
            stderr = proc.stderr
        except subprocess.TimeoutExpired:
            stdout = ""
            stderr = "Execution timed out after 15.0 seconds"

    full_output = stdout + "\n" + stderr

    # Parse test execution results from pytest verbose output
    results: List[TestResult] = []
    tests_written = 0
    tests_passed = 0
    tests_failed = 0

    # Match lines like: test_backend_generated.py::test_add_todo_accepts_title PASSED
    lines = stdout.splitlines()
    for line in lines:
        if "::" in line and ("PASSED" in line or "FAILED" in line or "ERROR" in line):
            tests_written += 1
            parts = line.split("::")
            test_name = parts[-1].split(" ")[0].strip()
            if "PASSED" in line:
                tests_passed += 1
                results.append(TestResult(test_name=test_name, passed=True, output=line.strip()))
            else:
                tests_failed += 1
                results.append(TestResult(test_name=test_name, passed=False, output=line.strip()))

    # Fallback if no verbose lines parsed (e.g. syntax error in test file)
    if tests_written == 0:
        # Count test functions in generated code
        func_matches = re.findall(r"def (test_[a-zA-Z0-9_]+)\(", pytest_code)
        tests_written = len(func_matches) if func_matches else 1
        tests_failed = tests_written
        results.append(TestResult(test_name="pytest_execution", passed=False, output=full_output))

    return QAReport(
        tests_written=tests_written,
        tests_passed=tests_passed,
        tests_failed=tests_failed,
        results=results,
    )
