"""
Pydantic schema definitions for Phase 1 codegen pipeline.

These schemas act as the single source of truth for communication contracts between pipeline stages.
Using strict typing ensures downstream agents (Backend, Frontend, Integration) consume standardized artifacts.
"""

from typing import Literal
from pydantic import BaseModel, Field


class Task(BaseModel):
    """
    Represents an individual task decomposed from a feature specification.
    
    Acceptance criteria are explicitly listed as strings so downstream LLM prompts
    and verification agents can validate completion against concrete expectations.
    """
    description: str = Field(description="Clear description of the work required for this task")
    acceptance_criteria: list[str] = Field(description="Concrete testable requirements for task completion")


class TaskList(BaseModel):
    """
    Structured breakdown of a feature spec into actionable engineering tasks.
    
    The PM Agent outputs this structure to establish operational scope before system design begins.
    """
    feature_spec: str = Field(description="Original feature specification prompt")
    tasks: list[Task] = Field(description="List of engineering tasks required to build the feature")


class EndpointSpec(BaseModel):
    """
    API endpoint specification designed by the Architect Agent.
    
    Restricting HTTP methods to standard REST verbs ensures generated backends adhere to convention
    and frontend fetch calls can be unambiguously validated.
    """
    path: str = Field(description="URL path pattern, e.g. /todos or /todos/{todo_id}")
    method: Literal["GET", "POST", "PUT", "DELETE"] = Field(description="HTTP request method")
    request_fields: dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of request body/query field names to type descriptions"
    )
    response_fields: dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of response payload field names to type descriptions"
    )
    description: str = Field(description="Purpose and behavior description of this endpoint")


class SystemContract(BaseModel):
    """
    The formal contract produced by the Architect Agent.
    
    This object constrains both Backend and Frontend generation agents.
    Because both code producers implement against this exact specification, cross-component
    incompatibilities (such as route mismatch or field name skew) are prevented by design.
    """
    feature_name: str = Field(description="High-level identifier for the feature being generated")
    endpoints: list[EndpointSpec] = Field(description="List of API endpoints required by the feature")
    data_models: dict[str, dict[str, str]] = Field(
        default_factory=dict,
        description="Shared data model schemas mapped by model name"
    )


class GeneratedComponent(BaseModel):
    """
    Metadata container for code artifacts written to disk by Backend or Frontend agents.
    
    Storing file_path enables downstream Integration and Verification agents to locate and inspect
    the generated code directly on disk rather than relying on transient string buffers.
    """
    component_name: Literal["backend", "frontend"] = Field(description="Type of component generated")
    file_path: str = Field(description="Absolute or relative file path to the generated source code on disk")
    summary: str = Field(description="Summary of generated component content and architecture")


class IntegrationResult(BaseModel):
    """
    Verification report generated by the Integration Agent.
    
    Tracks consistency status and highlights missing endpoint implementations on either side
    so automated test suites can perform deterministic assertions.
    """
    consistent: bool = Field(description="True if backend and frontend both implement all contract endpoints")
    missing_in_backend: list[str] = Field(default_factory=list, description="Endpoints missing in generated backend code")
    missing_in_frontend: list[str] = Field(default_factory=list, description="Endpoints missing in generated frontend code")
    notes: str = Field(description="Diagnostic notes summarizing contract verification results")
