"""
Pydantic schema definitions for Phase 1 codegen pipeline.

These schemas act as the single source of truth for communication contracts between pipeline stages.
Using strict typing ensures downstream agents (Backend, Frontend, Integration) consume standardized artifacts.
"""

from typing import Literal
from pydantic import BaseModel, Field


class Task(BaseModel):
    """
    Represents an individual task decomposed from a feature specification.
    
    Acceptance criteria are explicitly listed as strings so downstream LLM prompts
    and verification agents can validate completion against concrete expectations.
    """
    description: str = Field(description="Clear description of the work required for this task")
    acceptance_criteria: list[str] = Field(description="Concrete testable requirements for task completion")


class TaskList(BaseModel):
    """
    Structured breakdown of a feature spec into actionable engineering tasks.
    
    The PM Agent outputs this structure to establish operational scope before system design begins.
    """
    feature_spec: str = Field(description="Original feature specification prompt")
    tasks: list[Task] = Field(description="List of engineering tasks required to build the feature")


class EndpointSpec(BaseModel):
    """
    API endpoint specification designed by the Architect Agent.
    
    Restricting HTTP methods to standard REST verbs ensures generated backends adhere to convention
    and frontend fetch calls can be unambiguously validated.
    """
    path: str = Field(description="URL path pattern, e.g. /todos or /todos/{todo_id}")
    method: Literal["GET", "POST", "PUT", "DELETE"] = Field(description="HTTP request method")
    request_fields: dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of request body/query field names to type descriptions"
    )
    response_fields: dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of response payload field names to type descriptions"
    )
    description: str = Field(description="Purpose and behavior description of this endpoint")


class SystemContract(BaseModel):
    """
    The formal contract produced by the Architect Agent.
    
    This object constrains both Backend and Frontend generation agents.
    Because both code producers implement against this exact specification, cross-component
    incompatibilities (such as route mismatch or field name skew) are prevented by design.
    """
    feature_name: str = Field(description="High-level identifier for the feature being generated")
    endpoints: list[EndpointSpec] = Field(description="List of API endpoints required by the feature")
    data_models: dict[str, dict[str, str]] = Field(
        default_factory=dict,
        description="Shared data model schemas mapped by model name"
    )


class GeneratedComponent(BaseModel):
    """
    Metadata container for code artifacts written to disk by Backend or Frontend agents.
    
    Storing file_path enables downstream Integration and Verification agents to locate and inspect
    the generated code directly on disk rather than relying on transient string buffers.
    """
    component_name: Literal["backend", "frontend"] = Field(description="Type of component generated")
    file_path: str = Field(description="Absolute or relative file path to the generated source code on disk")
    summary: str = Field(description="Summary of generated component content and architecture")


class IntegrationResult(BaseModel):
    """
    Verification report generated by the Integration Agent.
    
    Tracks consistency status and highlights missing endpoint implementations on either side
    so automated test suites can perform deterministic assertions.
    """
    consistent: bool = Field(description="True if backend and frontend both implement all contract endpoints")
    missing_in_backend: list[str] = Field(default_factory=list, description="Endpoints missing in generated backend code")
    missing_in_frontend: list[str] = Field(default_factory=list, description="Endpoints missing in generated frontend code")
    notes: str = Field(description="Diagnostic notes summarizing contract verification results")


class TestResult(BaseModel):
    """
    Single pytest execution result captured by the QA Agent.
    """
    test_name: str = Field(description="Identifier or function name of the executed test")
    passed: bool = Field(description="True if test assertion succeeded, False if failed or error")
    output: str = Field(description="Captured stdout and stderr output from the test execution")


class QAReport(BaseModel):
    """
    Overall Quality Assurance execution report returned by the QA Agent.
    """
    tests_written: int = Field(description="Total number of pytest test functions written for acceptance criteria")
    tests_passed: int = Field(description="Number of test functions that passed execution")
    tests_failed: int = Field(description="Number of test functions that failed execution")
    results: list[TestResult] = Field(default_factory=list, description="Detailed test result objects")


class SecurityFinding(BaseModel):
    """
    Static analysis vulnerability finding reported by the Security Agent.
    """
    category: str = Field(description="Category of vulnerability (e.g., SQL Injection, Secrets, Input Validation)")
    severity: Literal["critical", "high", "medium", "low"] = Field(description="Severity classification rating")
    location: str = Field(description="File and line location or function context of finding")
    description: str = Field(description="Detailed explanation of the identified vulnerability")


class SecurityReport(BaseModel):
    """
    Comprehensive security scan report returned by the Security Agent.
    """
    findings: list[SecurityFinding] = Field(default_factory=list, description="List of identified security findings")
    critical_count: int = Field(description="Total number of findings classified as critical severity")


class DockerBuildResult(BaseModel):
    """
    Build result report returned by the DevOps Agent following docker build execution.
    """
    image_tag: str = Field(description="Target Docker image tag build identifier")
    build_succeeded: bool = Field(description="True if docker build command returned exit code 0")
    build_output: str = Field(description="Captured stdout/stderr build logs")
    build_duration_seconds: float = Field(description="Total time spent executing docker build in seconds")


class EndpointCheck(BaseModel):
    """
    Individual live HTTP endpoint validation check performed by the Validation Agent.
    """
    path: str = Field(description="Target URL endpoint path verified over real HTTP")
    method: str = Field(description="HTTP method used for verification request")
    actual_status: int = Field(description="HTTP status code received from live container server")
    passed: bool = Field(description="True if status code and payload response met contract requirements")
    notes: str = Field(description="Diagnostic details regarding endpoint validation check")


class ValidationReport(BaseModel):
    """
    Full live container runtime validation report returned by the Validation Agent.
    """
    image_tag: str = Field(description="Docker image tag used to launch validation container")
    container_started: bool = Field(description="True if container successfully started and bound to host port")
    endpoint_checks: list[EndpointCheck] = Field(default_factory=list, description="List of individual endpoint check reports")
    all_passed: bool = Field(description="True if container started and all endpoint checks passed")
    teardown_succeeded: bool = Field(description="True if container was cleanly stopped and removed without process leaks")


class PipelineRun(BaseModel):
    """
    Complete state representation of an end-to-end multi-agent pipeline execution.
    Handles graceful absence of Docker/Validation stages when Docker daemon is unavailable.
    """
    run_id: str = Field(description="Unique execution run identifier (UUID)")
    feature_spec: str = Field(description="Original natural language feature spec input")
    status: Literal["running", "completed", "failed"] = Field(description="Current execution status of pipeline")
    stages_completed: list[str] = Field(default_factory=list, description="List of agent stage names executed during this run")
    task_list: TaskList = Field(description="Decomposed task list artifact from PM Agent")
    system_contract: SystemContract = Field(description="Typed SystemContract artifact from Architect Agent")
    qa_report: QAReport = Field(description="Pytest execution report from QA Agent")
    security_report: SecurityReport = Field(description="Static vulnerability scan report from Security Agent")
    docker_build_result: DockerBuildResult | None = Field(default=None, description="Docker build result, or None if DevOps stage was skipped")
    validation_report: ValidationReport | None = Field(default=None, description="Live container validation report, or None if Validation stage was skipped")


class GitHubPublishPlan(BaseModel):
    """
    Publishing plan constructed by the GitHub Agent summarizing generated repository artifacts and PR metadata.
    """
    repo_name: str = Field(description="Target repository name")
    description: str = Field(description="Repository description summary")
    files_to_commit: list[str] = Field(default_factory=list, description="List of relative file paths to be committed")
    branch_name: str = Field(description="Target git feature branch name")
    pr_title: str = Field(description="Pull request title")
    pr_body: str = Field(description="Structured pull request body markdown")
    dry_run: bool = Field(description="True if created in dry-run mode without external GitHub API calls")
    actually_published: bool = Field(description="True if branch and pull request were published to live GitHub API")



